<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:tns="http://www.example.org/ns/intorder" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:ns0="http://www.example.org/ns/porder" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns1="http://oracle.com/sca/soapservice/POApplication/PoProcessing/ReceivePO"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/file/POApplication/PoProcessing/WritePOFileService"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/ReceivePO.wsdl"/>
            <oracle-xsl-mapper:rootElement name="PurchaseOrder" namespace="http://www.example.org/ns/porder"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/WritePOFileService.wsdl"/>
            <oracle-xsl-mapper:rootElement name="order" namespace="http://www.example.org/ns/intorder"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [WED JUL 06 18:11:27 CDT 2016].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:order>
         <tns:customerId>
            <xsl:value-of select="/ns0:PurchaseOrder/ns0:custID"/>
         </tns:customerId>
         <tns:orderId>
            <xsl:value-of select="/ns0:PurchaseOrder/ns0:ID"/>
         </tns:orderId>
         <tns:payMethod>
            <xsl:value-of select="/ns0:PurchaseOrder/ns0:payOption"/>
         </tns:payMethod>
         <tns:shipMethod>
            <xsl:value-of select="/ns0:PurchaseOrder/ns0:shipChoice"/>
         </tns:shipMethod>
         <tns:status>
            <xsl:value-of select="/ns0:PurchaseOrder/ns0:status"/>
         </tns:status>
         <tns:creditCard>
            <tns:cardType>
               <xsl:value-of select="/ns0:PurchaseOrder/ns0:ccType"/>
            </tns:cardType>
            <tns:cardNumber>
               <xsl:value-of select="/ns0:PurchaseOrder/ns0:ccNumber"/>
            </tns:cardNumber>
         </tns:creditCard>
         <tns:items>
            <xsl:for-each select="/ns0:PurchaseOrder/ns0:items/ns0:item">
               <tns:item>
                  <tns:prodId>
                     <xsl:value-of select="ns0:productId"/>
                  </tns:prodId>
                  <tns:prodName>
                     <xsl:value-of select="ns0:productName"/>
                  </tns:prodName>
                  <tns:price>
                     <xsl:value-of select="ns0:price"/>
                  </tns:price>
                  <tns:qty>
                     <xsl:value-of select="ns0:quantity"/>
                  </tns:qty>
               </tns:item>
            </xsl:for-each>
         </tns:items>
      </tns:order>
   </xsl:template>
</xsl:stylesheet>
