<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="GetMediator"
     targetNamespace="http://xmlns.oracle.com/Bpel/SalarioEmpleado/GetMediator"
     xmlns:tns="http://xmlns.oracle.com/Bpel/SalarioEmpleado/GetMediator"
     xmlns:inp1="http://erp.oracle.cenam"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://erp.oracle.cenam" schemaLocation="../Schemas/salario_schema.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="SetSalaryRequestMessage">
        <wsdl:part name="request" element="inp1:GetSalaryRequest"/>
    </wsdl:message>
    <wsdl:message name="GetSalaryResponseMessage">
        <wsdl:part name="response" element="inp1:GetSalaryResponse"/>
    </wsdl:message>
    <wsdl:portType name="SEExecute_ptt">
        <wsdl:operation name="SalaryEmployee">
            <wsdl:input message="tns:SetSalaryRequestMessage"/>
            <wsdl:output message="tns:GetSalaryResponseMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
