<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/ftp/AppServiceBus/ParseOffer/PutFileCsv" name="PutFileCsv-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="PutFileCsv.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/ftp/AppServiceBus/ParseOffer/PutFileCsv"/>
    <wsdl:binding name="PutFileCsv_ptt-binding" type="put:PutFileCsv_ptt" xmlns:put="http://xmlns.oracle.com/pcbpel/adapter/ftp/AppServiceBus/ParseOffer/PutFileCsv">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="PutFileCsv">
            <soap:operation soapAction="PutFileCsv"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>