<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns0="http://erp.oracle.cenam"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:tns="http://xmlns.oracle.com/Bpel/SalarioEmpleado/GetMediator"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:client="http://erp.oracle.cenam/Bpel/SalarioEmpleado/SalaryBPEL">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/GetMediator.wsdl"/>
        <oracle-xsl-mapper:rootElement name="GetSalaryRequest" namespace="http://erp.oracle.cenam"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/SalaryBPEL.wsdl"/>
        <oracle-xsl-mapper:rootElement name="GetSalaryRequest" namespace="http://erp.oracle.cenam"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [TUE MAY 24 13:33:09 CDT 2016].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <ns0:GetSalaryRequest>
      <xsl:if test="/ns0:GetSalaryRequest/noEmpleado">
        <noEmpleado>
          <xsl:value-of select="/ns0:GetSalaryRequest/noEmpleado"/>
        </noEmpleado>
      </xsl:if>
      <xsl:for-each select="/ns0:GetSalaryRequest/salarios">
        <salarios>
          <xsl:value-of select="."/>
        </salarios>
      </xsl:for-each>
      <xsl:for-each select="/ns0:GetSalaryRequest/impuestos">
        <impuestos>
          <xsl:value-of select="."/>
        </impuestos>
      </xsl:for-each>
      <xsl:for-each select="/ns0:GetSalaryRequest/deduccion">
        <deduccion>
          <xsl:value-of select="."/>
        </deduccion>
      </xsl:for-each>
    </ns0:GetSalaryRequest>
  </xsl:template>
</xsl:stylesheet>
