<?xml version='1.0' encoding='UTF-8'?>
<WL5G3N0:definitions name="AmazonWSServiceDefinitions" targetNamespace="http://com/wordpress/rathinasaba/aws" xmlns="" xmlns:WL5G3N0="http://schemas.xmlsoap.org/wsdl/" xmlns:WL5G3N1="http://com/wordpress/rathinasaba/aws" xmlns:WL5G3N2="http://schemas.xmlsoap.org/wsdl/soap/">
  <WL5G3N0:types>
    <xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://com/wordpress/rathinasaba/aws" xmlns:WL5G3N0="http://schemas.xmlsoap.org/wsdl/" xmlns:WL5G3N1="http://com/wordpress/rathinasaba/aws" xmlns:WL5G3N2="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xs="http://www.w3.org/2001/XMLSchema">
      <xs:element name="sendMsgToCloud">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="content" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="sendMsgToCloudResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="return" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:schema>
  </WL5G3N0:types>
  <WL5G3N0:message name="sendMsgToCloud">
    <WL5G3N0:part element="WL5G3N1:sendMsgToCloud" name="parameters"/>
  </WL5G3N0:message>
  <WL5G3N0:message name="sendMsgToCloudResponse">
    <WL5G3N0:part element="WL5G3N1:sendMsgToCloudResponse" name="parameters"/>
  </WL5G3N0:message>
  <WL5G3N0:portType name="AmazonWS">
    <WL5G3N0:operation name="sendMsgToCloud" parameterOrder="parameters">
      <WL5G3N0:input message="WL5G3N1:sendMsgToCloud"/>
      <WL5G3N0:output message="WL5G3N1:sendMsgToCloudResponse"/>
    </WL5G3N0:operation>
  </WL5G3N0:portType>
  <WL5G3N0:binding name="AmazonWSServiceSoapBinding" type="WL5G3N1:AmazonWS">
    <WL5G3N2:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <WL5G3N0:operation name="sendMsgToCloud">
      <WL5G3N2:operation style="document"/>
      <WL5G3N0:input>
        <WL5G3N2:body parts="parameters" use="literal"/>
      </WL5G3N0:input>
      <WL5G3N0:output>
        <WL5G3N2:body parts="parameters" use="literal"/>
      </WL5G3N0:output>
    </WL5G3N0:operation>
  </WL5G3N0:binding>
  <WL5G3N0:service name="AmazonWSService">
    <WL5G3N0:port binding="WL5G3N1:AmazonWSServiceSoapBinding" name="AmazonWSSoapPort">
      <WL5G3N2:address location="http://localhost:7001/AmazonWS/AmazonWS"/>
    </WL5G3N0:port>
  </WL5G3N0:service>
</WL5G3N0:definitions>